### ISSUE TITLE
cannot open the file /dev/interface, what's wrong ? 

### ISSUE THREAD

**Issue by zhoudayang** [scholtes/Lab6#1]

**Comment by scholtes** [comment]
@zhoudayang Hopefully you were able to figure it out, but in case not, some things you might try:

 * Did you load the kernel module? (after compiling, run `sudo insmod ./lab6.ko`)  
 * If you made changes and compiled, did you unload and reload the kernel module? (run `sudo rmmod lab6` and then load it again)  
* Look in `lab6.c`.  Could the device major/minor number be conflicting another device driver (this will likely not be the case unless you still have an old version of the `lab6` kernel module still installed)?  Could the device name "interface" be conflicting with another device driver (in that case, just name it to something else)?  

I'm on the road so I can't help much else, but I hope this list helps.
